# Generated by Django 2.2.7 on 2019-12-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20191130_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sender_name',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
